[project]
name = "{{cookiecutter.project_name}}"
description = "{{cookiecutter.description}}"
readme = "readme.md"
authors = [
    {name="{{cookiecutter.author}}", email="{{cookiecutter.email}}"}
]
license = {file = "license.md"}
requires-python = ">=3.9"